# Generated by Django 5.2.12 on 2026-06-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_cliente_ciudad_cliente_correo_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vendedores/'),
        ),
    ]
